[workspace]
members = [
    "contract",
    "meta"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
multiversx-sc = "0.50"
multiversx-sc-meta = "0.50"
