name: Rust CI

on:
  push:
    branches: [ main, develop, "feature/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy (warnings as errors)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Tests
        run: cargo test --all-features --verbose

      - name: Build WASM
        run: bash scripts/build-wasm.sh

      - name: Generate ABI
        run: bash scripts/gen-abi.sh

      - name: Upload artifacts (WASM + ABI)
        uses: actions/upload-artifact@v4
        with:
          name: foxleague-artifacts
          path: |
            target/wasm32-unknown-unknown/release/foxleague_sc.wasm
            meta/output/**
